"""add user_uid foreignkey to books

Revision ID: 0c43390b0ea7
Revises: d56d91743e9c
Create Date: 2025-05-21 12:38:29.912018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# TODO: add new this
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0c43390b0ea7'
down_revision: Union[str, None] = 'd56d91743e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'books', 'user_accounts', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user_uid')
    # ### end Alembic commands ###
