"""Add email file in the user table in the database

Revision ID: 3bc8f1e9e8a3
Revises: 77b6862b42f3
Create Date: 2025-05-13 17:42:34.071009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# TODO: add new this
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3bc8f1e9e8a3'
down_revision: Union[str, None] = '77b6862b42f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user_accounts', 'education')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('education', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_accounts', 'email')
    # ### end Alembic commands ###
