"""init

Revision ID: 77b6862b42f3
Revises: 
Create Date: 2025-05-13 17:40:05.212022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# TODO: add new this
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '77b6862b42f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('education', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'user_accounts', ['uid'])
    op.drop_column('user_accounts', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_accounts', type_='unique')
    op.drop_column('user_accounts', 'education')
    # ### end Alembic commands ###
