"""reviews table add

Revision ID: c01769abb920
Revises: 0c43390b0ea7
Create Date: 2025-05-21 21:14:02.634826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# TODO: add new this
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c01769abb920'
down_revision: Union[str, None] = '0c43390b0ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
