"""add role to users_accounts table

Revision ID: d56d91743e9c
Revises: 3bc8f1e9e8a3
Create Date: 2025-05-20 18:27:21.792428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# TODO: add new this
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd56d91743e9c'
down_revision: Union[str, None] = '3bc8f1e9e8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'role')
    # ### end Alembic commands ###
